version: '3.1'
services:
  solr:
    image: solr:7.4
    ports:
     - "8983:8983"
    volumes:
      # Please do before: sudo chown 8983:8983 /mnt/data/solr
      - "/mnt/data/solr:/opt/solr/server/solr/mycores"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
